# Site settings
title: Yellowstone Domes
email: 
description: Luxury Glamping Hotel in Paradise Valley
baseurl: "/pitch-yellowstone-site"
url: "https://willcan.github.io"

twitter_username:
github_username:

# Build settings
markdown: kramdown

plugins:
- jekyll-seo-tag
